#### Scalar -> 0 Dimentional Array/ tensor
 - Single number or only magnitude
 - e.g. temperature, height, weight

#### Vector -> 1D Array/ tensor
 - list of numbers -> algebric view
 - point in space -> geometric view

#### Matrix -> 2D Array/ tensor
 - table / dataset

#### Tensor -> ND Array/ tensor
 - Image -> height x width x channels
 -          224 X 224 X 3 (r, g, b)

### Numpy
Numerical Python

1. Python library used for working with arrays (Vectors, Matrices)
2. It has function for linear algebra, descriptive statistics.

#### why ?
- lists are slow in python 
- numpy array is 50X faster than list
- array of numpy -> ndarray
- Faster for matrix calculations
- stores elements in continuous memory location

In [22]:
import numpy as np

#### Datatypes in Numpy
+ int, float, bool(1bit), string, complex, unicode, object
+ Numeric types have precisions like 32-bit or 64-bit
+ Data can be represented using either Type or Type Code

|**Type**|**Type Code**|
|----|----|
|int8|i1|
|uint8|u1|
|int16|i2|
|uint16|u2|
|int32|u4|
|int64|i8|
|float16|f2|
|float32|f4|
|float64|f8|
|float128|f16|
|complex64|c8|
|complex128|c16|
|bool| None|
|object|o|
|unicode|U|
|string|s|

In [ ]:
import numpy as np

#-128 to 127

# arr = np.array([130,2,3,4,5], dtype=np.int8)
# arr = np.array([130,2,3,4,5], dtype="int8")
arr = np.array([-110,2,3,4,5], dtype="i1")
arr

array([-110,    2,    3,    4,    5], dtype=int8)

In [40]:
# unsigned
arr = np.array([220,2,3,4,5], dtype="uint8")
arr

array([220,   2,   3,   4,   5], dtype=uint8)

In [ ]:
# getting data type of ndarray
arr = np.array([220,6,3,4,5], dtype="int32")
arr.dtype

dtype('int32')

##### Creating Arrays

In [50]:
# ndarray - n dimentional array
arr = np.array([[220,3,4,5],[100,200,300,400], [100,200,300,400]], dtype="int32")
arr

array([[220,   3,   4,   5],
       [100, 200, 300, 400],
       [100, 200, 300, 400]], dtype=int32)

In [61]:
arr = np.zeros((5,5), dtype="int")
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [62]:
arr = np.ones((3,3,3))
arr

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [64]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [72]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [75]:
np.full((4,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [77]:
np.random.randint(1,1000,(5,5),'int16')

array([[569, 454, 553, 147, 233],
       [604, 411, 198, 652, 716],
       [ 89, 139, 926, 528, 403],
       [193, 821, 264, 104, 295],
       [536, 346,  38, 895, 585]], dtype=int16)

In [79]:
# returns value from 0-1 in float
np.random.rand(3,3)

array([[0.24824038, 0.68136735, 0.29734574],
       [0.44603877, 0.61861992, 0.95276912],
       [0.06001701, 0.61653012, 0.96443958]])

##### Inspecting Properties

In [84]:
arr = np.array([1.1, 2.2, 3.3, 4.4])
arr1 = arr.astype("int32")
# arr.dtype
arr1

array([1, 2, 3, 4], dtype=int32)

In [86]:
type(arr.tolist())

list

In [90]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9]], dtype="int16")
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int16)

In [91]:
arr.shape

(3, 3)

In [92]:
arr.size

9

In [93]:
arr.dtype

dtype('int16')

In [95]:
np.info(np.zeros)

zeros(shape, dtype=None, order='C', *, device=None, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: ``None``.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an a

In [2]:
import numpy as np
np.array([128,2,3], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.resize((4,4), refcheck=False).

In [13]:
# np.zeros((3,3))
# np.ones((3,5))
# np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

| **Type** | **Type Code** |
|----|----|
| int8 | i1 |

In [2]:
import numpy as np

In [3]:
arr = np.array([1.2,3.4,5.9], dtype=np.int16)
arr

array([1, 3, 5], dtype=int16)

In [28]:
arr = np.random.randint(1,100,(4,4), np.int32)
# np.random.rand(2,3,3)
arr.max(axis=1)

array([77, 99, 99, 88], dtype=int32)

In [31]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])